from __future__ import annotations

from dataclasses import dataclass

from tbia.domain.models import DataSource


@dataclass(frozen=True)
class SourceContract:
    source_id: str
    name: str
    owner: str
    access_method: str
    file_format: str
    grain: str
    geographic_coverage: str
    time_coverage: str
    refresh_cadence: str
    required_fields: tuple[str, ...]
    optional_fields: tuple[str, ...]
    code_systems: tuple[str, ...]
    missingness_rules: str
    duplicate_handling: str
    privacy_level: str
    validation_checks: tuple[str, ...]
    caveats: str

    def as_data_source(self) -> DataSource:
        return DataSource(
            source_id=self.source_id,
            name=self.name,
            owner=self.owner,
            access_method=self.access_method,
            format=self.file_format,
            grain=self.grain,
            privacy_level=self.privacy_level,
            refresh_cadence=self.refresh_cadence,
            caveats=self.caveats,
        )


SOURCE_CONTRACTS: tuple[SourceContract, ...] = (
    SourceContract(
        source_id="ibge_localidades",
        name="IBGE Localidades",
        owner="IBGE",
        access_method="HTTPS API",
        file_format="JSON",
        grain="municipality",
        geographic_coverage="Brazil",
        time_coverage="current territorial registry",
        refresh_cadence="as published by IBGE",
        required_fields=("id", "nome", "microrregiao.mesorregiao.UF.sigla"),
        optional_fields=("regiao-imediata", "regiao-intermediaria"),
        code_systems=("IBGE municipality code", "UF code"),
        missingness_rules="Reject municipality records without IBGE code, name, or UF.",
        duplicate_handling="Use IBGE municipality code as the natural key.",
        privacy_level="public aggregate metadata",
        validation_checks=("unique municipality code", "requested UF matches response UF"),
        caveats="Territorial boundaries and municipality registry can change over time.",
    ),
    SourceContract(
        source_id="ibge_population",
        name="IBGE population denominator",
        owner="IBGE",
        access_method="SIDRA/Agregados HTTPS API or CSV export",
        file_format="JSON/CSV",
        grain="municipality-year",
        geographic_coverage="Brazil",
        time_coverage="selected year",
        refresh_cadence="annual or census release",
        required_fields=("municipality_code", "year", "population"),
        optional_fields=("source_table",),
        code_systems=("IBGE municipality code",),
        missingness_rules="Reject rows with missing or non-positive population.",
        duplicate_handling="One population denominator per municipality-year-stratifier.",
        privacy_level="public aggregate denominator",
        validation_checks=("positive population", "municipality exists in Territory"),
        caveats="Population estimates and census values must not be mixed without metadata.",
    ),
    SourceContract(
        source_id="ibge_malhas",
        name="IBGE territorial meshes",
        owner="IBGE",
        access_method="IBGE Malhas HTTPS API",
        file_format="GeoJSON",
        grain="municipality geometry",
        geographic_coverage="Brazil",
        time_coverage="current territorial mesh",
        refresh_cadence="as published by IBGE",
        required_fields=("features[].properties.codarea", "features[].geometry"),
        optional_fields=("features[].id", "features[].properties.nome"),
        code_systems=("IBGE municipality code",),
        missingness_rules="Skip geometry features without a matched IBGE municipality code.",
        duplicate_handling="Use the latest matched geometry for each municipality code.",
        privacy_level="public aggregate metadata",
        validation_checks=("valid GeoJSON geometry object", "municipality exists in Territory"),
        caveats=(
            "Simplified web mesh for territorial visualization; not a source of patient or "
            "address-level location."
        ),
    ),
    SourceContract(
        source_id="ibge_intramunicipal",
        name="IBGE normalized intramunicipal public reference geometries",
        owner="IBGE or public municipal open-data source, normalized by TB-IA operator",
        access_method="Normalized GeoJSON under data/raw/public_sources/ibge_intramunicipal",
        file_format="GeoJSON",
        grain="public submunicipal reference geometry",
        geographic_coverage="selected public municipalities when available",
        time_coverage="source-specific public reference snapshot",
        refresh_cadence="manual refresh from public source",
        required_fields=(
            "features[].properties.territory_id",
            "features[].properties.name",
            "features[].properties.territory_type",
            "features[].properties.parent_id",
            "features[].properties.uf_code",
            "features[].properties.uf_sigla",
            "features[].geometry",
        ),
        optional_fields=("features[].properties.source_name", "features[].properties.source_year"),
        code_systems=("IBGE municipality code", "operator-defined public reference code"),
        missingness_rules=(
            "Skip features without required properties, a known municipality parent, or "
            "Polygon/MultiPolygon geometry."
        ),
        duplicate_handling="Use territory_id as the natural key; later files overwrite prior rows.",
        privacy_level="public aggregate/reference geography only",
        validation_checks=(
            "FeatureCollection",
            "Polygon or MultiPolygon geometry",
            "parent_id exists as a municipality",
            "territory_type is neighborhood_reference",
        ),
        caveats=(
            "Submunicipal public polygons are contextual reference geography only. They are "
            "not official health-team or microarea boundaries, and this public-data layer "
            "does not compute TB indicators, rankings, or scenarios at this level."
        ),
    ),
    SourceContract(
        source_id="sinan_tb",
        name="SINAN-TB / DATASUS",
        owner="Ministry of Health / DATASUS",
        access_method="DATASUS FTP DBC, TabNet PRN/HTML, or manual CSV fallback",
        file_format="DBC/DBF/CSV",
        grain="municipality-year aggregate",
        geographic_coverage="Brazil",
        time_coverage="selected notification or cohort year",
        refresh_cadence="DATASUS publication cadence; subject to delay",
        required_fields=(
            "municipality_code",
            "year",
            "notified_cases",
            "new_cases",
            "closed_cases",
            "cured_cases",
            "treatment_interruption_cases",
            "retreatment_cases",
            "new_pulmonary_cases",
            "lab_confirmed_pulmonary_cases",
            "hiv_tested_cases",
            "tb_hiv_cases",
            "trm_tb_cases",
            "retreatment_pulmonary_cases",
            "culture_retreated_cases",
        ),
        optional_fields=("source_period",),
        code_systems=("IBGE municipality code", "SINAN-TB dictionaries"),
        missingness_rules=(
            "Missing numeric metrics are treated as zero only in curated aggregate CSVs."
        ),
        duplicate_handling="Aggregate duplicate municipality-year rows by summing counts.",
        privacy_level="public aggregate or public anonymized microdata transformed to aggregate",
        validation_checks=("non-negative counts", "new cases <= notified cases when both exist"),
        caveats=(
            "Official mappings for entry type, closure, HIV, TRM-TB, and culture must be reviewed."
        ),
    ),
    SourceContract(
        source_id="sinan_validation",
        name="SINAN-TB mapping audit",
        owner="TB-IA",
        access_method="Generated from local DATASUS SINAN-TB DBF/DBC sample",
        file_format="JSON",
        grain="source-field audit report",
        geographic_coverage="selected UF",
        time_coverage="selected analysis year",
        refresh_cadence="generated during ingestion",
        required_fields=("field", "mapped_codes", "unmapped_values", "frequencies"),
        optional_fields=("caveat",),
        code_systems=("SINAN-TB public field codes",),
        missingness_rules="Blank values are reported as <blank> rather than discarded.",
        duplicate_handling="Frequency counts summarize all selected source records.",
        privacy_level="public technical audit over public anonymized microdata",
        validation_checks=("unmapped values reported", "record count reported"),
        caveats=(
            "Technical audit of current transform effects only; domain review against official "
            "SINAN-TB dictionaries and indicator handbooks is still required."
        ),
    ),
    SourceContract(
        source_id="indicator_validation",
        name="Indicator sanity validation",
        owner="TB-IA",
        access_method="Generated after indicator computation",
        file_format="JSON",
        grain="indicator invariant report",
        geographic_coverage="selected analysis scope",
        time_coverage="selected analysis year",
        refresh_cadence="generated during indicator computation",
        required_fields=(
            "status",
            "indicator_count",
            "violation_count",
            "warning_count",
            "violations",
            "warnings",
        ),
        optional_fields=("caveats",),
        code_systems=("TB-IA indicator IDs",),
        missingness_rules=(
            "Suppressed public values remain null but retain numerator and denominator metadata."
        ),
        duplicate_handling="One report per analysis year is overwritten on recomputation.",
        privacy_level="public aggregate validation metadata",
        validation_checks=(
            "non-negative counts",
            "zero denominators reported",
            "bounded proportions do not exceed their denominator",
            "unsuppressed percentages remain between 0 and 100",
        ),
        caveats=(
            "Mechanical invariant report only; formula and dictionary choices still require "
            "public health domain review."
        ),
    ),
    SourceContract(
        source_id="sim",
        name="SIM mortality",
        owner="Ministry of Health / DATASUS",
        access_method="DATASUS FTP DBC or manual CSV fallback",
        file_format="DBC/DBF/CSV",
        grain="municipality-year aggregate",
        geographic_coverage="Brazil",
        time_coverage="selected death year",
        refresh_cadence="DATASUS publication cadence; subject to delay",
        required_fields=("municipality_code", "year", "tb_deaths"),
        optional_fields=("source_period",),
        code_systems=("IBGE municipality code", "CID-10 A15-A19"),
        missingness_rules="Reject rows with missing municipality, year, or death count.",
        duplicate_handling="Aggregate duplicate municipality-year rows by summing deaths.",
        privacy_level="public aggregate",
        validation_checks=("non-negative deaths",),
        caveats=("Filter should use underlying cause CID-10 A15-A19 for the mortality indicator."),
    ),
    SourceContract(
        source_id="sih_sus",
        name="SIH/SUS hospital admissions",
        owner="Ministry of Health / DATASUS",
        access_method="DATASUS FTP DBC or manual CSV fallback",
        file_format="DBC/DBF/CSV",
        grain="municipality-year aggregate",
        geographic_coverage="Brazil",
        time_coverage="selected admission year/months",
        refresh_cadence="monthly publication subject to delay",
        required_fields=("municipality_code", "year", "tb_admissions"),
        optional_fields=("source_period",),
        code_systems=("IBGE municipality code", "CID-10 A15-A19"),
        missingness_rules="Reject rows with missing municipality, year, or admission count.",
        duplicate_handling="Aggregate duplicate municipality-year rows by summing admissions.",
        privacy_level="public aggregate",
        validation_checks=("non-negative admissions",),
        caveats="Hospitalization is a severity or care-pathway proxy, not an incidence measure.",
    ),
    SourceContract(
        source_id="cnes",
        name="CNES facility and capacity snapshot",
        owner="Ministry of Health / DATASUS",
        access_method="DATASUS FTP DBC or manual CSV fallback",
        file_format="DBC/DBF/CSV",
        grain="facility-month snapshot",
        geographic_coverage="Brazil",
        time_coverage="selected month",
        refresh_cadence="monthly publication subject to delay",
        required_fields=("facility_id", "municipality_code", "name", "facility_type"),
        optional_fields=("sus_linked",),
        code_systems=("CNES", "IBGE municipality code"),
        missingness_rules="Reject rows without CNES code or municipality.",
        duplicate_handling="Use latest snapshot per facility for the selected period.",
        privacy_level="public facility metadata",
        validation_checks=("unique facility code", "municipality exists in Territory"),
        caveats="CNES capacity proxies require domain review before operational interpretation.",
    ),
    SourceContract(
        source_id="local_territories",
        name="Local territory registry",
        owner="Municipal pilot synthetic source",
        access_method="CSV under data/raw/municipal_demo",
        file_format="CSV",
        grain="local territory",
        geographic_coverage="synthetic municipal pilot",
        time_coverage="pilot snapshot",
        refresh_cadence="manual demo refresh",
        required_fields=(
            "territory_id",
            "name",
            "territory_type",
            "parent_id",
            "uf_code",
            "uf_sigla",
            "facility_id",
            "team_id",
        ),
        optional_fields=(),
        code_systems=("local territory code", "UF code"),
        missingness_rules="Reject rows without territory code, type, UF, or metadata name.",
        duplicate_handling="Reject duplicate territory_id values.",
        privacy_level="synthetic local operational metadata",
        validation_checks=("required columns", "forbidden personal identifiers"),
        caveats="Territory and team names are operational labels, not person names.",
    ),
    SourceContract(
        source_id="local_teams",
        name="Local team registry",
        owner="Municipal pilot synthetic source",
        access_method="CSV under data/raw/municipal_demo",
        file_format="CSV",
        grain="team",
        geographic_coverage="synthetic municipal pilot",
        time_coverage="pilot snapshot",
        refresh_cadence="manual demo refresh",
        required_fields=("team_id", "facility_id", "name", "team_type", "active"),
        optional_fields=(),
        code_systems=("local team code", "facility code"),
        missingness_rules=(
            "Reject rows without team code, facility code, team label, type, or status."
        ),
        duplicate_handling="Reject duplicate team_id values.",
        privacy_level="synthetic local operational metadata",
        validation_checks=("required columns", "boolean active flag"),
        caveats="Team names are operational labels and must not contain person identifiers.",
    ),
    SourceContract(
        source_id="local_tb_cases",
        name="Pseudonymized local TB cases",
        owner="Municipal pilot synthetic source",
        access_method="CSV under data/raw/municipal_demo",
        file_format="CSV",
        grain="pseudonymized local TB case",
        geographic_coverage="synthetic municipal pilot",
        time_coverage="selected analysis year",
        refresh_cadence="manual demo refresh",
        required_fields=(
            "local_case_id",
            "pseudonymized_patient_id",
            "territory_id",
            "facility_id",
            "team_id",
            "notification_date",
            "diagnosis_date",
            "treatment_start_date",
            "entry_type",
            "clinical_form",
            "closure_status",
            "closure_date",
            "rifampicin_resistance",
            "retreatment",
            "previous_treatment_failure",
        ),
        optional_fields=(),
        code_systems=("local case code", "local pseudonym"),
        missingness_rules="Reject rows without case code, pseudonym, territory, dates, or flags.",
        duplicate_handling="Reject duplicate local_case_id values.",
        privacy_level="pseudonymized synthetic local operational data",
        validation_checks=("required columns", "date parsing", "forbidden identifiable columns"),
        caveats="No CPF, CNS, person name, address, or phone column is accepted.",
    ),
    SourceContract(
        source_id="local_lab_events",
        name="Pseudonymized local lab events",
        owner="Municipal pilot synthetic source",
        access_method="CSV under data/raw/municipal_demo",
        file_format="CSV",
        grain="pseudonymized lab event",
        geographic_coverage="synthetic municipal pilot",
        time_coverage="selected analysis year",
        refresh_cadence="manual demo refresh",
        required_fields=(
            "local_lab_id",
            "local_case_id",
            "pseudonymized_patient_id",
            "test_type",
            "request_date",
            "collection_date",
            "result_date",
            "result",
            "status",
        ),
        optional_fields=(),
        code_systems=("local lab code", "local case code"),
        missingness_rules=(
            "Reject rows without lab code, case code, pseudonym, test type, request date, "
            "or status."
        ),
        duplicate_handling="Reject duplicate local_lab_id values.",
        privacy_level="pseudonymized synthetic local operational data",
        validation_checks=("required columns", "date parsing", "forbidden identifiable columns"),
        caveats="Laboratory alerts are operational signals for human review.",
    ),
    SourceContract(
        source_id="local_pharmacy_dispensing",
        name="Pseudonymized pharmacy dispensing",
        owner="Municipal pilot synthetic source",
        access_method="CSV under data/raw/municipal_demo",
        file_format="CSV",
        grain="pseudonymized dispensing event",
        geographic_coverage="synthetic municipal pilot",
        time_coverage="selected analysis year",
        refresh_cadence="manual demo refresh",
        required_fields=(
            "dispensing_id",
            "local_case_id",
            "pseudonymized_patient_id",
            "dispensing_date",
            "days_supplied",
            "medication_group",
        ),
        optional_fields=(),
        code_systems=("local dispensing code", "local case code"),
        missingness_rules=(
            "Reject rows without dispensing code, case code, pseudonym, date, or days supplied."
        ),
        duplicate_handling="Reject duplicate dispensing_id values.",
        privacy_level="pseudonymized synthetic local operational data",
        validation_checks=(
            "required columns",
            "positive days_supplied",
            "forbidden identifiable columns",
        ),
        caveats="Pickup-delay alerts are operational review signals, not adherence diagnoses.",
    ),
    SourceContract(
        source_id="local_contacts",
        name="Pseudonymized contact investigations",
        owner="Municipal pilot synthetic source",
        access_method="CSV under data/raw/municipal_demo",
        file_format="CSV",
        grain="pseudonymized contact investigation",
        geographic_coverage="synthetic municipal pilot",
        time_coverage="selected analysis year",
        refresh_cadence="manual demo refresh",
        required_fields=(
            "contact_id",
            "index_case_id",
            "pseudonymized_contact_id",
            "identified_date",
            "evaluation_date",
            "symptomatic",
            "tpt_started_date",
            "status",
        ),
        optional_fields=(),
        code_systems=("local contact code", "local case code"),
        missingness_rules=(
            "Reject rows without contact code, index case, pseudonym, identified date, or status."
        ),
        duplicate_handling="Reject duplicate contact_id values.",
        privacy_level="pseudonymized synthetic local operational data",
        validation_checks=("required columns", "date parsing", "forbidden identifiable columns"),
        caveats="Contact queues must be reviewed by authorized municipal professionals.",
    ),
    SourceContract(
        source_id="local_resources",
        name="Local resource inventory",
        owner="Municipal pilot synthetic source",
        access_method="CSV under data/raw/municipal_demo",
        file_format="CSV",
        grain="facility resource snapshot",
        geographic_coverage="synthetic municipal pilot",
        time_coverage="selected analysis year",
        refresh_cadence="manual demo refresh",
        required_fields=(
            "facility_id",
            "sputum_collection",
            "rapid_molecular_access",
            "xray_access",
            "sample_transport",
            "pharmacy_tb_meds",
            "chw_count",
        ),
        optional_fields=(),
        code_systems=("facility code",),
        missingness_rules="Reject rows without facility code, resource flags, or CHW count.",
        duplicate_handling="Reject duplicate facility_id values for the selected year.",
        privacy_level="synthetic local resource metadata",
        validation_checks=("required columns", "boolean flags", "non-negative CHW count"),
        caveats=(
            "Resource inventory supports operational interpretation and requires local validation."
        ),
    ),
    SourceContract(
        source_id="operational_alerts",
        name="Generated operational alerts",
        owner="TB-IA",
        access_method="Generated from pseudonymized local pilot CSVs",
        file_format="SQLite",
        grain="alert",
        geographic_coverage="synthetic municipal pilot",
        time_coverage="selected analysis year and reference date",
        refresh_cadence="generated on demand",
        required_fields=("alert_id", "alert_type", "severity", "status", "local_case_id"),
        optional_fields=("due_date",),
        code_systems=("local case code", "local alert type"),
        missingness_rules="Generated only for cases linked to local operational records.",
        duplicate_handling="Replace generated alerts for the selected year on rebuild.",
        privacy_level="pseudonymized operational decision-support signal",
        validation_checks=("deterministic rule output", "no patient pseudonym in API rows"),
        caveats="Alerts are review queues and must not be treated as diagnosis or prescription.",
    ),
)


def get_source_contract(source_id: str) -> SourceContract:
    for contract in SOURCE_CONTRACTS:
        if contract.source_id == source_id:
            return contract
    raise KeyError(f"unknown source contract: {source_id}")
